[build]
  functions = "src/dashboard/functions"
  command = "cd src/dashboard && npm run functions:build && npm run build"
  publish = "src/dashboard/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
